export default {
  CELL_SIZE: 50,
  CELL_GAP: 0,
  CANVAS_WIDTH: 900,
  CANVAS_HEIGHT: 600,
  TOWER_COST: 100,
  ENEMY_SPAWN_INTERVAL: 600,
  ENEMY_STARTING_POPULATION: 50,
  STARTING_WAVE_SIZE: 10,
  WAVE_GROWTH: 3,
  PLAYER_STARTING_RESOURCES: 300,
  FLOATING_TEXT_LIFESPAN: 50,
  MOUSE_CONFIG: {
    MOUSE_STARTING_X: 10,
    MOUSE_STARTING_Y: 10,
    MOUSE_WIDTH: 0.1,
    MOUSE_HEIGHT: 0.1,
  },
};
